version: '2'

services:

  cmxnotificationreceiver:
    build: ./
    restart: on-failure
    container_name: cmxnotificationreceiver
    ports:
     - "0.0.0.0:5004:5004"
    volumes:
     - .:/cmxnotificationreceiver
    mem_limit: 100M

  ngrok:
    container_name: ngrok
    ports:
      - "0.0.0.0:4040:4040"
    image: wernight/ngrok
    links:
      - "cmxnotificationreceiver"
    environment:
      - NGROK_PORT=cmxnotificationreceiver:5004
    mem_limit: 100M
